#!/usr/bin/env python

# Copyright (C) k736, inc. All Rights Reserved.
# Unauthorized copying or redistribution of this file is strictly prohibited.

from roy import build, deps
from pkg_common import Common

class Directory(Common):

    def __init__(self):
        self.name = "datawire-directory"
        self.build_deps = []
        self.deps = [deps.datawire]
        self.version = "0.2"
        self.arch = "all"
        self.conf = ["/etc/datawire/directory.conf"]

    def build(self, distro):
        result = self.install_prep()
        result += self.install_script("directory")
        result += self.install_config(self.name, distro.image)
        return result

build(Directory())
