#!/usr/bin/env python

# Copyright 2015 datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from roy import build, deps
from pkg_common import Common

class Datawire(Common):

    def __init__(self):
        self.name = "datawire"
        self.build_deps = []
        self.deps = [deps.datawire_proton]
        self.arch = "all"
        self.conf = ["/etc/datawire/datawire.conf"]

    def build(self, distro):
        result = self.install_prep()
        result += """
cp -r datawire /work/install/opt/datawire/lib
"""
        result += self.install_script("dw")
        result += self.install_config(self.name)
        return result

build(Datawire())
