#!/usr/bin/env python

# Copyright 2015 datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from roy import build, deps


class Proton:

    def __init__(self):
        self.name = "datawire-proton"
        self.build_deps = [deps.patch, deps.make, deps.gcc, deps.cmake,
                           deps.uuid.dev, deps.ssl.dev, deps.swig,
                           deps.python.dev]
        self.deps = [deps.uuid, deps.ssl, deps.python]
        self.version = "0.11-datawire-1"

    def setup(self, env):
        env.system("wget -nv https://github.com/datawire/qpid-proton/archive/%s.zip -O %s/proton.zip" %
                   (self.version, env.work))
        env.system("cd %s; unzip -o proton.zip" % env.work)
        env.system("cd %s; mv qpid-proton-%s proton" % (env.work, self.version))

    def build(self, distro):
        result = """
set -e

cd proton

patch -s CMakeLists.txt <<CMAKEPATCH
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -77,6 +77,8 @@ set (SYSCONF_INSTALL_DIR etc CACHE PATH "System read only configuration director
 set (SHARE_INSTALL_DIR share CACHE PATH "Shared read only data directory")
 set (MAN_INSTALL_DIR share/man CACHE PATH "Manpage directory")
 
+set (CMAKE_INSTALL_RPATH \${CMAKE_INSTALL_PREFIX}/\${LIB_INSTALL_DIR})
+
 mark_as_advanced (INCLUDE_INSTALL_DIR LIB_INSTALL_DIR SYSCONF_INSTALL_DIR SHARE_INSTALL_DIR MAN_INSTALL_DIR)
 
 ## LANGUAGE BINDINGS
CMAKEPATCH

mkdir -p build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/datawire -DLIB_SUFFIX=""
make && make install DESTDIR=/work/install
"""
        return result

build(Proton())
