#!/usr/bin/env python

# Copyright (C) k736, inc. All Rights Reserved.
# Unauthorized copying or redistribution of this file is strictly prohibited.

from roy import build, deps
from pkg_common import Common

class Datawire(Common):

    def __init__(self):
        self.name = "datawire"
        self.build_deps = []
        self.deps = [deps.datawire_proton]
        self.arch = "all"
        self.conf = ["/etc/datawire/datawire.conf"]

    def build(self, distro):
        result = self.install_prep()
        result += """
cp -r datawire /work/install/opt/datawire/lib
"""
        result += self.install_script("dw")
        result += self.install_config(self.name)
        return result

build(Datawire())
