#!/usr/bin/env python

from argparse import ArgumentParser
from proton.reactor import Reactor
from datawire import Address, Tether, Sender, Stream

class Fanout:

    def __init__(self, args):
        self.tether = Tether(args.directory, args.address, args.physical)
        self.physical = Address(args.physical)
        self.stream = Stream()
        self.senders = [Sender(target, self.stream) for target in args.targets]
        self.handlers = [self.stream]

    def on_reactor_init(self, event):
        event.reactor.acceptor(self.physical.host, self.physical.port)
        self.tether.start(event.reactor)
        for sender in self.senders:
            sender.start(event.reactor)

parser = ArgumentParser(prog="recv")
parser.add_argument("-d", "--directory", default="//localhost/directory", help="datawire directory")
parser.add_argument("-p", "--physical", default="//localhost:5678", help="physical address")
parser.add_argument("address", help="service address")
parser.add_argument("targets", nargs='+', help="target addresses")

Reactor(Fanout(parser.parse_args())).run()
