#!/usr/bin/env python

import logging
from argparse import ArgumentParser
from proton.reactor import Reactor
from datawire import Processor, Receiver

class Client:

    def __init__(self, args):
        self.receiver = Receiver(args.address, Processor(self))

    def on_reactor_init(self, event):
        self.receiver.start(event.reactor)

    def on_message(self, event):
        print event.message

logging.basicConfig(level=logging.WARNING)

parser = ArgumentParser(prog="pull")
parser.add_argument("address", help="source address")

Reactor(Client(parser.parse_args())).run()
