#!/usr/bin/env python

import sys, time
from argparse import ArgumentParser
from proton.reactor import Reactor
from datawire import Sender

class Client:

    def __init__(self, args):
        self.sender = Sender(args.address)

    def on_reactor_init(self, event):
        self.sender.start(event.reactor)
        self.sender.send("Hello World!")
        self.sender.close()

parser = ArgumentParser(prog="send")
parser.add_argument("address", help="target address")

Reactor(Client(parser.parse_args())).run()
