#!/usr/bin/env python

import sys, time
from argparse import ArgumentParser
from proton.reactor import Reactor
from proton import Endpoint
from datawire import Stream, Container

class Logger:

    def on_unhandled(self, name, event):
        print name, event

class Autoclose:

    def on_drained(self, event):
        event.link.close()

class Client:

    def __init__(self, args):
        self.stream = Stream()
        self.me = Container(self.stream)
        self.me.sender(args.address)
        self.handlers = [self.me]

    def on_reactor_init(self, event):
        self.me.start(event.reactor)
        self.stream.put("Hello World!")
        self.stream.close()

parser = ArgumentParser(prog="send")
parser.add_argument("address", help="amqp address")

Reactor(Client(parser.parse_args())).run()
