#!/usr/bin/env python

import logging
from argparse import ArgumentParser
from proton.reactor import Reactor
from datawire import Sender

class Client:

    def __init__(self, args):
        self.sender = Sender(args.address)

    def on_reactor_init(self, event):
        self.sender.start(event.reactor)
        self.sender.send("Hello World!")
        # closing the sender will automatically stop it when any
        # buffered messages have been sent
        self.sender.close()

logging.basicConfig(level=logging.DEBUG)

parser = ArgumentParser(prog="send")
parser.add_argument("address", help="target address")

Reactor(Client(parser.parse_args())).run()
