/**
 * Copyright (C) k736, inc. All Rights Reserved.
 * Unauthorized copying or redistribution of this file is strictly prohibited.
 */
package io.datawire;

/**
 * Handler methods for events generated by datawire. An implementation of this
 * interface is required to forward all events it does not want to implement to
 * the
 * {@link org.apache.qpid.proton.engine.Handler#onUnhandled(org.apache.qpid.proton.engine.Event)}
 * To facilitate this it is recommended for handler classes to extend the
 * {@link BaseHandler} which just forwards all events to the onUnhandled method.
 * 
 * @author bozzo
 *
 */
public interface DatawireHandler extends org.apache.qpid.proton.engine.Handler {
    /**
     * The method invoked for {@link DatawireEvent.Type#MESSAGE} events. These events
     * are generated by the {@link Decoder} handler.
     * 
     * @param e
     *            The event where the message is accessible through the
     *            {@link DatawireEvent#getMessage()}
     */
    public void onMessage(DatawireEvent e);

    /**
     * The method invoked for {@link DatawireEvent.Type#SAMPLE} events. These events are generated by the {@link Sampler} handler.
     * 
     * @param e An event that references the {@link DatawireEvent#getLink()} that needs sampling.
     */
    public void onSample(DatawireEvent e);

    /**
     * The method invoked for {@link DatawireEvent.Type#DRAINED} events. There events are generated by the {@link Sender} and {@link Receiver} handlers.
     * @param event An event that references the {@link DatawireEvent#getLink()} that is drained.
     */
    public void onDrained(DatawireEvent event);
}
